### PR TITLE
MWPW-128105 - stage.adobe.com + MILO libs

### PR DESCRIPTION
**Pull request by draganatrajkovic**
Resolve: https://jira.corp.adobe.com/browse/MWPW-128105

According from the @JFernandezAdobe requirement, files which were coming from _main-milo-adobecom.hlx.page_ before, now are coming from  _www.adobe.com_. 
With this change, www.stage.adobe.com will use production code (www.adobe.com), but with _?milolibs_ param it can be set to use _main--milo--adobecom.hlx.page/libs_ or _localhost/libs_.

I put the label 'do not merge' because I need confirmation that libs should come from _www.adobe.com_ and not from _http://www.stage.adobe.com_

Test URLs (test once the changes are published):
- https://www.stage.adobe.com/acrobat/online/jpg-to-pdf.html
- https://www.stage.adobe.com/acrobat/online/jpg-to-pdf.html?milolibs=local (milo should be run locally)
- https://www.stage.adobe.com/acrobat/online/jpg-to-pdf.html?milolibs=mwpw-125487-header-font-size-howto--milo--draganatrajkovic
- https://www.stage.adobe.com/acrobat/online/jpg-to-pdf.html?milolibs=share-block-updates
- https://www.adobe.com/acrobat/online/pdf-to-ppt.html

### CODE REVIEW

**Review by Blainegunn — APPROVED** [review]

**Review by seanchoi-dev — CHANGES_REQUESTED** [review]
`libs` needs to be assigned for each case otherwise `getLibs` will be undefined.

**Comment by draganatrajkovic** [comment]
> `libs` needs to be assigned for each case otherwise `getLibs` will be undefined.

Thank you. Please review now

**Review by seanchoi-dev — CHANGES_REQUESTED** [review]
This makes sense and looks ok to me but.. this is also getting more off from original function from milo-college(https://github.com/adobecom/milo-college/blob/main/scripts/utils.js#L16-L30)

Can we do simply add one line of code from original function..? Something like this?:
`if (branch === 'main' && hostname === 'www.stage.adobe.com') return 'https://www.adobe.com/libs';`

So, the function will be like:

```
export const [setLibs, getLibs] = (() => {
  let libs;
  return [
    (prodLibs, location) => {
      libs = (() => {
        const { hostname, search } = location || window.location;
        if (!(hostname.includes('.hlx.') || hostname.includes('local'))) return prodLibs;
        const branch = new URLSearchParams(search).get('milolibs') || 'main';
        if (branch === 'main' && hostname === 'www.stage.adobe.com') return 'https://www.adobe.com/libs';
        if (branch === 'local') return 'http://localhost:6456/libs';
        return branch.includes('--') ? `https://${branch}.hlx.live/libs` : `https://${branch}--milo--adobecom.hlx.live/libs`;
      })();
      return libs;
    }, () => libs,
  ];
})();
```

**Comment by draganatrajkovic** [comment]
> This makes sense and looks ok to me but.. this is also getting more off from original function from milo-college(https://github.com/adobecom/milo-college/blob/main/scripts/utils.js#L16-L30)
> 
> Can we do simply add one line of code from original function..? Something like this?: `if (branch === 'main' && hostname === 'www.stage.adobe.com') return 'https://www.adobe.com/libs';`
> 
> So, the function will be like:
> 
> ```
> export const [setLibs, getLibs] = (() => {
>   let libs;
>   return [
>     (prodLibs, location) => {
>       libs = (() => {
>         const { hostname, search } = location || window.location;
>         if (!(hostname.includes('.hlx.') || hostname.includes('local'))) return prodLibs;
>         const branch = new URLSearchParams(search).get('milolibs') || 'main';
>         if (branch === 'main' && hostname === 'www.stage.adobe.com') return 'https://www.adobe.com/libs';
>         if (branch === 'local') return 'http://localhost:6456/libs';
>         return branch.includes('--') ? `https://${branch}.hlx.live/libs` : `https://${branch}--milo--adobecom.hlx.live/libs`;
>       })();
>       return libs;
>     }, () => libs,
>   ];
> })();
> ```
> 
> I haven't tested above yet, but it seems same logic to me.

Thank you @seanchoi-dev . Can you, please, review now?

**Review by zagi25 — APPROVED** [review]

**Comment by draganatrajkovic** [comment]
> Did you test with my suggested function? I still see the outdated code... like
> 
> ```
> const stageEnvs = ['localhost', 'hlx.page', 'hlx.live', 'stage.adobe.com'];
> if (!stageEnvs.some((env) => hostname.includes(env))) {
>   return prodLibs;
> }
> ```
> 
> Wondering if you have reason to keep them.



> if (!(hostname.includes('.hlx.') || hostname.includes('local'))) return prodLibs;

With:
`if (!(hostname.includes('.hlx.') || hostname.includes('local'))) return prodLibs;`
is not covered case when hostname is stage.adobe.com, it will return prodLibs

**Comment by draganatrajkovic** [comment]
@seanchoi-dev 
Please take a look now.
I added 'stage' 
`        if (!(hostname.includes('.hlx.') || hostname.includes('local') || hostname.includes('stage'))) return prodLibs;
`
without that it is not possible test some branch with ?milolibs param

**Comment by seanchoi-dev** [comment]
> 

I approved it but do you have the test URL that having the issue you mentioned? I am kinda curious.

**Pull request merged**
