### PR TITLE
Minimize waterfall prior to fetching the widget

### PR DESCRIPTION
**Pull request by peller**
inline small modules and defer modules which aren't yet needed, such as review and browser redirect

@Blainegunn

### CODE REVIEW

**Comment by TsayAdobe** [comment]
The script has multiple syntax errors and the browser won't load it.

**Comment by peller** [comment]
@TsayAdobe where do I find those syntax errors?

**Comment by TsayAdobe** [comment]
* langLocaleMap is undefined
* Callback for IMS:Ready should be async since there is await inside.
* Callback for Bowser:Ready should be async since there is await inside.

Try dc-converter-widget.test.js (remove ".skip") to see if the widget can be loaded.

**Comment by peller** [comment]
see #201

**Pull request closed without merging**
