### PR TITLE
MWPW-163699 Use a locale map for prefetch

### PR DESCRIPTION
**Pull request by TsayAdobe**
* Use the locale map for the prefetch URL
* CSS updates for RTL

Resolves: [MWPW-163699](https://jira.corp.adobe.com/browse/MWPW-163699)

**Test URLs**
US: https://mwpw-163699--dc--adobecom.hlx.page/acrobat/online/sign-pdf
JP: https://mwpw-163699--dc--adobecom.hlx.page/jp/acrobat/online/test/sign-pdf

### CODE REVIEW

**Comment by Ruchika4** [comment]
Hi @TsayAdobe we fetch the locale and region code and pass it to unity here https://github.com/adobecom/dc/blob/stage/acrobat/blocks/unity/unity.js#L125 which also has localeMap. Can we keep this mapping at one common place for maintainability purpose?

**Review by peller — APPROVED** [review]

**Comment by TsayAdobe** [comment]
> Hi @TsayAdobe we fetch the locale and region code and pass it to unity here https://github.com/adobecom/dc/blob/stage/acrobat/blocks/unity/unity.js#L125 which also has localeMap. Can we keep this mapping at one common place for maintainability purpose?

@Ruchika4 Can you make it external? Those entries probably should be separated into region and language. Verb-widget uses `region/language`.

**Comment by peller** [comment]
> > Hi @TsayAdobe we fetch the locale and region code and pass it to unity here https://github.com/adobecom/dc/blob/stage/acrobat/blocks/unity/unity.js#L125 which also has localeMap. Can we keep this mapping at one common place for maintainability purpose?
> 
> @Ruchika4 Can you make it external? Those entries probably should be separated into region and language. Verb-widget uses `region/language`.

I believe we have a request to Unity to make the redirect URL available. We shouldn't duplicate this logic or the url content.
@sanjayms01

**Comment by TsayAdobe** [comment]
@Ruchika4 I updated the code to use the localeMap from `unity.js`

**Review by Ruchika4 — APPROVED** [review]

**Comment by peller** [comment]
we don't just want the locale map from unity. We want to share the entire redirect url @TsayAdobe @Ruchika4

**Review by sanjayms01 — APPROVED** [review]

**Pull request merged**
