### PR TITLE
MWPW-160929: Match desktop CTA shape on mobile

### PR DESCRIPTION
**Pull request by joaquinrivero**
Resolves: [MWPW-160929](https://jira.corp.adobe.com/browse/MWPW-160929)

Test URL:

- https://main--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?martech=off
- https://mwpw-160929--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf?martech=off

### CODE REVIEW

**Review by Blainegunn — APPROVED** [review]
perfect

**Comment by Blainegunn** [comment]
@joaquinrivero why?

**Comment by Blainegunn** [comment]
why?

**Review by TsayAdobe — APPROVED** [review]

**Review by tedAir — APPROVED** [review]
Verified with https://mwpw-160929--dc--adobecom.hlx.page/acrobat/online/test/sign-pdf that the CTA shapes in both Portrait and Landscape modes on iPhone and Android are the same.

**Pull request merged**
