### PR TITLE
MWPW-140457 add *.adobe.io to frame-src for downloads

### PR DESCRIPTION
**Pull request by peller**
https://wiki.corp.adobe.com/pages/viewpage.action?spaceKey=DEX&title=Impact+on+Direct+file+Upload+and+Downloads+for+ACP+Users

### CODE REVIEW

**Review by TsayAdobe — COMMENTED** [review]
`*.adobe.io` or `*.adobe.com`?

**Comment by peller** [comment]
> `*.adobe.io` or `*.adobe.com`?

adobe.io

**Review by TsayAdobe — APPROVED** [review]

**Review by zagi25 — APPROVED** [review]

**Review by joaquinrivero — APPROVED** [review]

**Comment by joaquinrivero** [comment]
If we are changing from ". amazonaws.com" domain to ". adobe.io". , amazonaws.com needs to be removed in some point?

**Comment by peller** [comment]
Yes I think so at some point. I don’t feel safe doing it now

**Pull request merged**
