### PR TITLE
updated redirect link

### PR DESCRIPTION
**Pull request by saragajic11**
https://mobile-widget-fix-pdf-editor-redirect--dc--adobecom.hlx.page/acrobat/online/pdf-editor

### CODE REVIEW

**Review by joaquinrivero — APPROVED** [review]

**Comment by Blainegunn** [comment]
@saragajic11 
the values for the goURLs and analytics fields aren't the same. 
We need to make a map or goURLs and redirects separately. 
In analytics the value should be `add-comment`.

for example: 
```
acrobat:verb-add-comment:goto-app:clicked
```
Whereas the goUrls is `addcomment`.

for example: 
```
https://www.adobe.com/go/acrobat-addcomment
```
If this fix needs to go out today I'll update this PR.

**Review by Blainegunn — CHANGES_REQUESTED** [review]
see my comments

**Comment by saragajic11** [comment]
> @saragajic11 the values for the goURLs and analytics fields aren't the same. We need to make a map or goURLs and redirects separately. In analytics the value should be `add-comment`.
> 
> for example:
> 
> ```
> acrobat:verb-add-comment:goto-app:clicked
> ```
> 
> Whereas the goUrls is `addcomment`.
> 
> for example:
> 
> ```
> https://www.adobe.com/go/acrobat-addcomment
> ```
> 
> If this fix needs to go out today I'll update this PR.

Hi @Blainegunn check my last commit: https://github.com/adobecom/dc/pull/776/commits/c1fb249931d1e0c291290ad3a8c2d17c6f6da7bc

**Review by Blainegunn — APPROVED** [review]
TY!

**Review by peller — APPROVED** [review]

**Pull request merged**
