### PR TITLE
MWPW-140549: CLS on drag and drop or quick file selection

### PR DESCRIPTION
**Pull request by joaquinrivero**
### Changes Made:
Addressed the CLS (Cumulative Layout Shift) issue related to the widget moving from 70px to 30px briefly when a user tries to upload a file immediately after clicking the main CTA.
Reviews is not longer visible during file processing, preventing CLS spikes.

### How to Test:
Throttle your Chrome to slow 3G or fast 3G.
Visit one of the "problem" pages, e.g., https://www.adobe.com/acrobat/online/compress-pdf.html.
Wait for the main CTA to become enabled (no longer grey).
Click on the CTA and try to upload a file.
Verify that the widget no longer moving, reviews disappears meanwhile file is processed  and that there is no significant CLS spike.

Resolves: [MWPW-140549](https://jira.corp.adobe.com/browse/MWPW-140549)

### Test URLs:

PDF to Word    
Before: https://www.adobe.com/acrobat/online/pdf-to-word.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/pdf-to-word

PDF to JPG    
Before: https://www.adobe.com/acrobat/online/pdf-to-jpg.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/pdf-to-jpg

PDF to Excel    
Before: https://www.adobe.com/acrobat/online/pdf-to-excel.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/pdf-to-excel

PDF to PPT    
Before: https://www.adobe.com/acrobat/online/pdf-to-ppt.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/pdf-to-ppt

PDF to converter    
Before: https://www.adobe.com/acrobat/online/convert-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/convert-pdf

Word to PDF    
Before: https://www.adobe.com/acrobat/online/word-to-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/word-to-pdf

Jpg to PDF    
Before: https://www.adobe.com/acrobat/online/jpg-to-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/jpg-to-pdf

PNG to PDF    
Before: https://www.adobe.com/acrobat/online/png-to-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/png-to-pdf

Excel to PDF    
Before: https://www.adobe.com/acrobat/online/excel-to-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/excel-to-pdf

PPT to PDF    
Before: https://www.adobe.com/acrobat/online/ppt-to-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/ppt-to-pdf

Compress PDF    
Before: https://www.adobe.com/acrobat/online/compress-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/compress-pdf

Merge PDFs    
Before: https://www.adobe.com/acrobat/online/merge-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/merge-pdf

Split PDF    
Before: https://www.adobe.com/acrobat/online/split-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/split-pdf

Crop a PDF    
Before: https://www.adobe.com/acrobat/online/crop-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/crop-pdf

Delete PDF pages    
Before: https://www.adobe.com/acrobat/online/delete-pdf-pages.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/delete-pdf-pages

Rearrange PDF pages    
Before: https://www.adobe.com/acrobat/online/rearrange-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/rearrange-pdf

Extract PDF pages    
Before: https://www.adobe.com/acrobat/online/extract-pdf-pages.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/extract-pdf-pages

Insert PDF pages    
Before: https://www.adobe.com/acrobat/online/add-pages-to-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/add-pages-to-pdf

Number PDF pages    
Before: https://www.adobe.com/acrobat/online/add-pdf-page-numbers.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/add-pdf-page-numbers

Protect password    
Before: https://www.adobe.com/acrobat/online/password-protect-pdf.html
After: https://mwpw-140549--dc--adobecom.hlx.live/acrobat/online/password-protect-pdf

### CODE REVIEW

**Review by peller — APPROVED** [review]
🔥

**Comment by peller** [comment]
Is MWPW-137866 the right ticket?

**Comment by joaquinrivero** [comment]
@peller  this is the correct one [MWPW-140549](https://jira.corp.adobe.com/browse/MWPW-140549)

**Comment by Blainegunn** [comment]
@joaquinrivero thank you so much! If you have time would you mind resolved the css linting errors too please.

**Review by Blainegunn — APPROVED** [review]

**Pull request merged**
