### PR TITLE
MWPW-129156 Fix verb footer style

### PR DESCRIPTION
**Pull request by TsayAdobe**
Resolves: https://jira.corp.adobe.com/browse/MWPW-129156

Before: https://www.adobe.com/acrobat/online/pdf-to-ppt

After: https://mwpw-129156--dc--adobecom.hlx.page/acrobat/online/pdf-to-ppt

### CODE REVIEW

**Comment by seanchoi-dev** [comment]
I am looking how Milo does and wondering if we should if from Milo side.

**Review by seanchoi-dev — CHANGES_REQUESTED** [review]
Looks like this doesn't make the result as same as what consonant suggests.
image

I would actually remove this css block (.accordion-container.verb-subfooter-moblie .accordion-trigger { }
) since Milo already provides the consonant style as default.

**Comment by TsayAdobe** [comment]
@seanchoi-dev My Chrome and Safari don't render the section like your screenshot.

**Comment by seanchoi-dev** [comment]
> @seanchoi-dev My Chrome and Safari don't render the section like your screenshot. 

I am not sure which screenshot you're referring to... but my last screenshot is the result when I removed all css inside `.accordion-container.verb-subfooter-moblie .accordion-trigger { }`

**Review by Blainegunn — APPROVED** [review]
looks great @TsayAdobe

**Pull request merged**
